### ISSUE TITLE
source_catalogs.info() fails, as catalogue is missing

### ISSUE THREAD

**Issue by GernotMaier** [gammapy/gammapy#1233]
(probably a minor thing)

I am following the examples for source catalogues and objects on http://docs.gammapy.org/en/latest/catalog/index.html 

>>> from gammapy.catalog import source_catalogs
>>> source_catalogs.info()
Source catalog registry:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/gammapy/catalog/registry.py", line 93, in info
    self.info_table.pprint()
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/gammapy/catalog/registry.py", line 103, in info_table
    cat = self[name]
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/gammapy/catalog/registry.py", line 81, in __getitem__
    self._loaded_catalogs[name] = factory(*args)
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/gammapy/catalog/fermi.py", line 744, in __init__
    table = Table.read(filename, hdu='LAT_Point_Source_Catalog')
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/astropy/table/table.py", line 2521, in read
    out = io_registry.read(cls, *args, **kwargs)
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/astropy/io/registry.py", line 516, in read
    fileobj = ctx.__enter__()
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/Users/maierg/anaconda/envs/python36/lib/python3.6/site-packages/astropy/utils/data.py", line 206, in get_readable_fileobj
    fileobj = io.FileIO(name_or_obj, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/maierg/Experiments/Gamma/gammapy-extra/datasets/catalogs/fermi/gll_psch_v11.fit.gz'
>>> .q
  File "<stdin>", line 1

gll_psch_v11.fit.gz is missing in the datasets provided with gammapy-extra, only those are available

gll_psch_v07.fit.gz
gll_psch_v08.fit.gz
gll_psch_v13.fit.gz

using gammapy 0.6

**Comment by cdeil** [comment]
@GernotMaier - Please update to the latest development version of Gammapy.

There are several open issues in Gammapy concerning the handling of test data and that the two repos `gammapy` and `gammapy-extra` should be version-coupled or that we should access data in an entirely different way. We are aware of this problem, and we will fix it, but not immediately.

I'm closing this issue now.
