### ISSUE TITLE
Input validation and better errors from map initialisers

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1624]
@robertazanin and I were very confused for a while by this (actually in a more complex setting, here just a minimal example):

```python
>>> from gammapy.maps import Map, WcsNDMap
>>> m = Map.create()
>>> geom = Map.from_geom(m.geom)
>>> WcsNDMap(geom)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/work/code/gammapy/gammapy/maps/wcsnd.py", line 51, in __init__
    shape = tuple([np.max(geom.npix[0]), np.max(geom.npix[1])] +
AttributeError: 'WcsNDMap' object has no attribute 'npix'
```

This is a usage error, where we pass a `map` object instead of a `geom` object to the `WcsNDMap` initialiser.

Overall the init / copy / from_geom is pretty complex, and I've made several such mistakes in the past days.

Maybe we can add type checks as input validation, and fail early with good error messages?

Putting this as a reminder under the v0.9 milestone.

**Comment by maxnoe** [comment]
This is a huge and general problem for new users. Gammapy errors in general are very unhelpful and usually come from deep in the hierarchy from classes, usually something like `NoneType has no attribute XY`.

One has to be very familiar with the gammapy codebase to be able to understand what the problem is.

Input needs to be validated at the first possible moment and errors should be clear of what is missing or wrong. Otherwise users will just get frustrated and stop trying to use gammapy.

**Comment by registerrier** [comment]
Reviving this issue, independently of the general issue of type validation, should we at least provide type checking on all `Maps` constructor to ensure that all `geom` are of the correct type?

**Comment by bkhelifi** [comment]
This standard python error is not explicit enough? Python does the check already... Do we need additional lines of code? 
If we do this for `Maps`, the constructors of each class (and even the parameters of each function) should be improved by following our principle of code homogeneity. The amount of additional lines is huge... ;(

**Comment by maxnoe** [comment]
> This standard python error is not explicit enough? 

As written above, no.

How is a user not deeply familar with the gammapy internals diagnose what they need to change when they get a 

 `NoneType has no attribute 'table'`

error?

**Comment by bkhelifi** [comment]
I get your point... This has obviously a huge implication for all classes (and function). To be discussed.... Thanks for this report

**Comment by adonath** [comment]
This could be addressed as part of a `gammapy.maps` refactoring for v2.0.

**Comment by registerrier** [comment]
Input validation is generally needed. It has been improved in a few places, but we need  more specific issues to apply in a consistent manner. Closing for now.
