### ISSUE TITLE
Crash of 'gammapy download tutorials' under ubuntu

### ISSUE THREAD

**Issue by bkhelifi** [gammapy/gammapy#1831]
Hello,

I have tried to download the tutorials with the online command and it crashed:

```[5:13pm] /home/bruno/MesProgrammes/gammapy> gammapy download tutorials
Traceback (most recent call last):
  File "/home/bruno/MesProgrammes/anaconda3/bin//gammapy", line 11, in <module>
    load_entry_point('gammapy==0.8.dev7279', 'console_scripts', 'gammapy')()
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/bruno/MesProgrammes/gammapy/gammapy/scripts/download.py", line 64, in cli_download_tutorials
    downnotebooks.files()
  File "/home/bruno/MesProgrammes/gammapy/gammapy/scripts/downloadclass.py", line 60, in files
    jsondata = json.loads(urlopen(url_dat).read())
  File "/home/bruno/MesProgrammes/anaconda3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Have you encountered this issue?
For information, I am managing my env with conda and I did a 'git pull' 2h ago. And I am using then:
``` Used API: 
gammapy: 0.8.dev7480
astropy: 3.0.4
sherpa: 4.10.0
minuit: 1.3.2
```

Cheers,
Bruno

**Comment by cdeil** [comment]
@Bultako - I think `urlopen.read()` is returning bytes and `json.loads` is expecting str, so this is a real bug. Why didn't this appear for everyone on PYthon 3?

Solution would be to `.decode("utf-8")`, no?

**Comment by Bultako** [comment]
@bkhelifi 
Thanks for catching this.
I have made a commit to `master` trying to resolve it.
I have re-activated the tests for the downloading scripts hoping to catch it also in Travis CI.

@bkhelifi 
please make a pull and tell us if it is fixed.

**Comment by bkhelifi** [comment]
Hi all,
Thanks for your fast answers. I have tried it again after a git pull. The script is fixed and it works. Well done.
I close the issue!
Bruno
