### ISSUE TITLE
gammapy download HTTP error

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#1958]
@Bultako - I'm doing the v0.9 release today, and after making the release tarball and testing it locally I got this error:
```
$ python -m gammapy --log-level=debug download datasets
Traceback (most recent call last):
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/deil/work/code/gammapy/dist/gammapy-0.9/gammapy/__main__.py", line 14, in <module>
    sys.exit(cli())  # pylint:disable=no-value-for-parameter
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/deil/work/code/gammapy/dist/gammapy-0.9/gammapy/scripts/download.py", line 42, in cli_download_datasets
    downloadproc.files()
  File "/Users/deil/work/code/gammapy/dist/gammapy-0.9/gammapy/scripts/downloadclass.py", line 69, in files
    self.parse_yaml()
  File "/Users/deil/work/code/gammapy/dist/gammapy-0.9/gammapy/scripts/downloadclass.py", line 157, in parse_yaml
    r = urlopen(url_nbs)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

So it's failing here:
https://github.com/gammapy/gammapy/blob/ec8bb9fc2056c3cb2c6ab01a353cffa13d6d2430/gammapy/scripts/downloadclass.py#L157

I guess I have to add a new file `gammapy-0.9-tutorials.yml` here?
https://github.com/gammapy/gammapy-webpage/tree/gh-pages/download/tutorials
@Bultako - What is the recommended way to prepare that file?

For now I'll add some `log.info` or `log.debug` statements to the Gammapy download code, to always log which file it will try to fetch, since that info isn't mentioned in the `HTTPError` and traceback.

I know that `cta_sensitivity.ipynb` and `image_fitting_with_sherpa.ipynb` are currently broken; the idea was to just leave them as-is and not remove / hide them for v0.9, they aren't used much and will be fixed for v0.10.

**Comment by cdeil** [comment]
I've added some log statements in e5dde582 . So now one can see which file is not found:
```
$ python -m gammapy download datasets
INFO:gammapy.scripts.downloadclass:Download: https://gammapy.org/download/tutorials/gammapy-0.9-tutorials.yml
Traceback (most recent call last):
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/deil/work/code/gammapy/gammapy/__main__.py", line 14, in <module>
    sys.exit(cli())  # pylint:disable=no-value-for-parameter
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/deil/work/code/gammapy/gammapy/scripts/download.py", line 42, in cli_download_datasets
    downloadproc.files()
  File "/Users/deil/work/code/gammapy/gammapy/scripts/downloadclass.py", line 70, in files
    self.parse_yaml()
  File "/Users/deil/work/code/gammapy/gammapy/scripts/downloadclass.py", line 159, in parse_yaml
    txt = urlopen(url).read().decode("utf-8")
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Users/deil/software/anaconda3/envs/gammapy-dev/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by cdeil** [comment]
Ah, I think I figured out how to make `gammapy-0.9-tutorials.yml`. I'll put that now as a copy of `notebooks.yml` from master, use that for testing, and then change the URLs in there only after tagging v0.9.

**Comment by Bultako** [comment]
@cdeil 

> Ah, I think I figured out how to make gammapy-0.9-tutorials.yml. I'll put that now as a copy of notebooks.yml from master, use that for testing, and then change the URLs in there only after tagging v0.9.

Yes that's how I would do it.

> I now see https://gammapy.org/download/tutorials/gammapy-0.9-tutorials.yml working in my browser, but trying to fetch it with urlopen or curl gives a 404. Are they someone not seeing the latest version of the website!??? I'll try again later today.

I do not have this problem.
I have successfully used ``gammapy download`` to fetch the v0.9 version of the notebooks.
Thanks for the code improvement, by the way :)

> I know that cta_sensitivity.ipynb and image_fitting_with_sherpa.ipynb are currently broken; the idea was to just leave them as-is and not remove / hide them for v0.9, they aren't used much and will be fixed for v0.10.

Keep in mind that the yaml file lists the tutorials to deliver when using `gammapy download`, whilst the whole content of the `tutorials` folder is used to generate HTML-notebooks with Sphinx, we decide which ones are *visible* the list of the in `/docs/tutorials.rst` file.

`cta_sensitivity.ipynb` is not in the list of notebooks to deliver, but we have `image_fitting_with_sherpa.ipynb` is the list, if it is broken maybe we should remove it from the list?

FYI --
Others notebooks shipped, these ones broken because using *special data* are:

- fermi_lat.ipynb
No such file or directory: '$GAMMAPY_FERMI_LAT_DATA/3fhl/allsky/fermi_3fhl_events_selected.fits.gz'

- spectrum_pipe.ipynb
No such file or directory: '$GAMMA_CAT/output/gammacat.fits.gz'

- sed_fitting_gammacat_fermi.ipynb
No such file or directory: '$GAMMA_CAT/output/gammacat.fits.gz'
