### ISSUE TITLE
SSLError on gammapy download

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2428]
I have high-speed internet, yet I'm getting this SSLError for gammapy download.

@Bultako or anyone - Thoughts?

```
(gammapy-0.14) hfm-1804a:temp deil$ gammapy download tutorials --release 0.14
INFO:gammapy.scripts.downloadclasses:Looking for notebooks...
INFO:gammapy.scripts.downloadclasses:Downloading https://gammapy.org/download/install/gammapy-0.14-environment.yml
INFO:gammapy.scripts.downloadclasses:Reading https://gammapy.org/download/tutorials/gammapy-0.14-tutorials.yml
INFO:gammapy.scripts.downloadclasses:Content will be downloaded in gammapy-tutorials/notebooks-0.14
Files Downloaded: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29/29 [00:01<00:00, 16.87file/s]
                                                                                                                                                                               
INFO:gammapy.scripts.downloadclasses:Looking for scripts...                                                                                                                    
INFO:gammapy.scripts.downloadclasses:Downloading https://gammapy.org/download/install/gammapy-0.14-environment.yml                                                             
INFO:gammapy.scripts.downloadclasses:Reading https://gammapy.org/download/tutorials/gammapy-0.14-scripts.yml                                                                   
INFO:gammapy.scripts.downloadclasses:Content will be downloaded in gammapy-tutorials/scripts-0.14                                                                              
Files Downloaded: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.14file/s]
                                                                                                                                                                               
INFO:gammapy.scripts.downloadclasses:Looking for datasets...
INFO:gammapy.scripts.downloadclasses:Reading https://gammapy.org/download/tutorials/gammapy-0.14-tutorials.yml
INFO:gammapy.scripts.downloadclasses:Reading https://gammapy.org/download/data/gammapy-0.14-data-index.json
INFO:gammapy.scripts.downloadclasses:Content will be downloaded in gammapy-tutorials/datasets
Files Downloaded:  46%|█████████████████████████████████████████████████████▉                                                              | 204/439 [00:22<00:22, 10.40file/s]ERROR:asyncio:SSL error in data received                                                                                                                                       
protocol: <asyncio.sslproto.SSLProtocol object at 0x105f03be0>                                                                                                                 
transport: <_SelectorSocketTransport fd=26 read=polling write=<idle, bufsize=0>>                                                                                               
Traceback (most recent call last):                                                                                                                                             
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/asyncio/sslproto.py", line 526, in data_received                            | 0.00/4.17M [00:00<?, ?B/s]
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Files Downloaded:  77%|█████████████████████████████████████████████████████████████████████████████████████████                           | 337/439 [00:37<00:12,  8.17file/sERROR:asyncio:SSL error in data received                                                                                                                                        
protocol: <asyncio.sslproto.SSLProtocol object at 0x10737de10>                                                                                                                 
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>████████████▎                                             | 20.8M/39.3M [00:08<00:10, 1.76MB/s]
Traceback (most recent call last):                                                                                                                                             
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/asyncio/sslproto.py", line 526, in data_received                                                        
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
                                                                                                                                                                              ERROR:asyncio:SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x105f03c88>
transport: <_SelectorSocketTransport fd=27 read=polling write=<idle, bufsize=0>>████████████▊                                             | 21.0M/39.3M [00:08<00:09, 1.84MB/s]
Traceback (most recent call last):
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/asyncio/sslproto.py", line 526, in data_received                             | 0.00/551k [00:00<?, ?B/s]
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/asyncio/sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)
Files Downloaded: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 439/439 [00:51<00:00,  8.47file/s]
                                                                                                                                                                               
*** Enter the following commands below to get started with this version of Gammapy                                                                                             
cd gammapy-tutorials                                                                                                                                                           
conda env create -f gammapy-0.14-environment.yml                                                                                                                               
conda activate gammapy-0.14                                                                                                                                                    
jupyter lab

*** You might want to declare GAMMAPY_DATA env variable
export GAMMAPY_DATA=/Users/deil/temp/gammapy-tutorials/datasets-0.14
```

**Comment by Bultako** [comment]
It seems this issue has been already spotted on `aiohttp` library: 
https://github.com/aio-libs/aiohttp/issues/3535

I managed to fix it with a temporary patch https://github.com/gammapy/gammapy-webpage/commit/7d61b7dffcc1eed2e8de6910eb669abf5566a822

In the meantime, I think we can keep the issue open.

**Comment by adonath** [comment]
@Bultako Is this still relevant?

**Comment by Bultako** [comment]
Once we will merge PR https://github.com/gammapy/gammapy/pull/3153 this issue will not be longer relevant.

**Comment by Bultako** [comment]
Closing, since PR #3153 removed `parfive` dependency and hence potentials SSL errors in `aiohttp` library.
