### ISSUE TITLE
Fix or remove gammapy.test() function

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#2429]
The `gammapy.test()` function, and the `gammapy check runtests` command are broken since the removal of astropy-helpers.

This is a reminder issue for myself to try and bring it back using pytest directly,, or if it's not possible (say within a day of work), remove those.

```
(gammapy-0.14) hfm-1804a:notebooks-0.14 deil$ gammapy check runtests
Traceback (most recent call last):
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/bin/gammapy", line 11, in <module>
    sys.exit(cli())
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/gammapy/scripts/check.py", line 23, in cli_check_runtests
    test(verbose=True)
TypeError: test() got an unexpected keyword argument 'verbose'
(gammapy-0.14) hfm-1804a:notebooks-0.14 deil$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import gammapy
>>> gammapy.test()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/deil/software/anaconda3/envs/gammapy-0.14/lib/python3.7/site-packages/gammapy/__init__.py", line 47, in test
    raise NotImplementedError
NotImplementedError
```

**Comment by adonath** [comment]
For now I decided to just remove it https://github.com/gammapy/gammapy/commit/bd22a220d834da28624ba2542792117260d05588
