### ISSUE TITLE
Ring analysis fails on the latest dev

### ISSUE THREAD

**Issue by AtreyeeS** [gammapy/gammapy#2971]
Fitting a `MapDatasetOnOff` fails on the latest dev with the following message:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-103-559861c4719a> in <module>
      1 fit = Fit([stacked_on_off])
----> 2 result = fit.run()

~/Gammapy-dev/gammapy/gammapy/modeling/fit.py in run(self, backend, optimize_opts, covariance_opts)
    105         if optimize_opts is None:
    106             optimize_opts = {}
--> 107         optimize_result = self.optimize(backend, **optimize_opts)
    108 
    109         if covariance_opts is None:

~/Gammapy-dev/gammapy/gammapy/modeling/fit.py in optimize(self, backend, **kwargs)
    165         # and return something simpler, not a tuple of three things
    166         factors, info, optimizer = compute(
--> 167             parameters=parameters, function=self.datasets.stat_sum, **kwargs
    168         )
    169 

~/Gammapy-dev/gammapy/gammapy/modeling/iminuit.py in optimize_iminuit(parameters, function, **kwargs)
     53     minuit.tol = tol
     54     minuit.strategy = strategy
---> 55     minuit.migrad(**migrad_opts)
     56 
     57     factors = minuit.args

src/iminuit/_libiminuit.pyx in iminuit._libiminuit.Minuit.migrad()

RuntimeError: exception was raised in user function
User function arguments:
    par_000_amplitude = +1.000000
        par_001_lon_0 = +3.202786
        par_002_lat_0 = -1.071159
        par_003_sigma = +1.000000
Original python exception in user function:
AttributeError: 'MapDatasetOnOff' object has no attribute 'use_cache'
  File "/Users/asinha/Gammapy-dev/gammapy/gammapy/modeling/iminuit.py", line 17, in fcn
    return self.function()
  File "/Users/asinha/Gammapy-dev/gammapy/gammapy/datasets/core.py", line 173, in stat_sum
    stat_sum += dataset.stat_sum()
  File "/Users/asinha/Gammapy-dev/gammapy/gammapy/datasets/map.py", line 1646, in stat_sum
    return Dataset.stat_sum(self)
  File "/Users/asinha/Gammapy-dev/gammapy/gammapy/datasets/core.py", line 53, in stat_sum
    stat = self.stat_array()
  File "/Users/asinha/Gammapy-dev/gammapy/gammapy/datasets/map.py", line 1487, in stat_array
    mu_sig = self.npred().data
  File "/Users/asinha/Gammapy-dev/gammapy/gammapy/datasets/map.py", line 344, in npred
    if self.use_cache is False:
```

I suppose it can be fixed by adding `use_cache=self.use_cache` in `MapDaasetOnOff.from_map_dataset()` and adding the same on `init` ?

**Comment by adonath** [comment]
Thanks @AtreyeeS, it seems the fitting of a `MapDatasetOnOff` is not covered by our tests? The issue does not appear locally nor on the CI builds....

**Comment by adonath** [comment]
As discussed in the dev meeting I'll remove the `use_cache` and `evaluation_mode` from the `MapDataset`, we can still modify it directly on the `MapEvaluator`

**Comment by adonath** [comment]
This specific issue should be resolved by https://github.com/gammapy/gammapy/pull/2972. @AtreyeeS could you possibly still add a little unit test to run a fit using `MapDatasetOnOff`? Just avoid that a similar issue comes up in future...

**Comment by AtreyeeS** [comment]
Added in #2988
