### ISSUE TITLE
gammapy 0.18.2 environment has python requirement 3.7.0, breaking jupyter notebook

### ISSUE THREAD

**Issue by maxnoe** [gammapy/gammapy#3193]
The gammapy 0.18.2 environment that one should download in the installation instructions has the line

```
  - python=3.7.0
```

The current version of 3.7 is 3.7.9 and 3.7.0 had a bug that prevented juputer notebooks from starting, resulting in this error:

```
❯ jupyter notebook
[I 14:07:18.893 NotebookApp] JupyterLab extension loaded from /home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/site-packages/jupyterlab
[I 14:07:18.894 NotebookApp] JupyterLab application directory is /home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/share/jupyter/lab
[I 14:07:18.896 NotebookApp] Serving notebooks from local directory: /home/maxnoe/Projects/gammapy-tutorials
[I 14:07:18.896 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 14:07:18.896 NotebookApp] http://localhost:8888/?token=35127264abaa0268cdb104dbea1b0b3f8e918abe4de01a4c
[I 14:07:18.896 NotebookApp]  or http://127.0.0.1:8888/?token=35127264abaa0268cdb104dbea1b0b3f8e918abe4de01a4c
[I 14:07:18.896 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.start()
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/site-packages/notebook/notebookapp.py", line 2269, in start
    self.launch_browser()
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/site-packages/notebook/notebookapp.py", line 2200, in launch_browser
    browser = webbrowser.get(self.browser or None)
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/webbrowser.py", line 42, in get
    register_standard_browsers()
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/webbrowser.py", line 567, in register_standard_browsers
    cmd = _synthesize(cmdline, -1)
  File "/home/maxnoe/.local/anaconda/envs/gammapy-0.18.2/lib/python3.7/webbrowser.py", line 116, in _synthesize
    register(browser, None, controller, update_tryorder)
TypeError: register() takes from 2 to 3 positional arguments but 4 were given
```

The env file should just remove the bugfix version of the python version (and probably also of many other depedencies):

**Comment by adonath** [comment]
Thanks @maxnoe! On my machine I cannot reproduce this issue...However I fully agree, we shouldn't be strict on the Python version in our env files and only specify a bugfix version, if it is required to fix a known issue. Do you adapt the env files @Bultako? Or should I?

**Comment by maxnoe** [comment]
See this: https://github.com/jupyter/jupyter/issues/357

Can you reproduce the issue when you e.g. do `export BROWSER=firefox`?

**Comment by adonath** [comment]
No, I still cannot reproduce the issue. The following environment works fine for me:
```
System:

	python_executable      : /Users/adonath/software/anaconda3/envs/gammapy-0.18.2/bin/python 
	python_version         : 3.7.0      
	machine                : x86_64     
	system                 : Darwin     


Gammapy package:

	version                : 0.18.2     
	path                   : /Users/adonath/software/anaconda3/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy 


Other packages:

	numpy                  : 1.19.4     
	scipy                  : 1.4.1      
	astropy                : 4.1        
	regions                : 0.4        
	click                  : 7.0        
	yaml                   : 5.2        
	IPython                : 7.10.2     
	jupyterlab             : 2.0.1      
	matplotlib             : 3.2.1      
	pandas                 : 0.25.3     
	healpy                 : 1.13.0     
	iminuit                : 1.3.8      
	sherpa                 : 4.12.0     
	naima                  : 0.9.1      
	emcee                  : 2.2.1      
	corner                 : 2.0.1      
	parfive                : 1.0.2      
```

And output of `jupyter --version`:
```
jupyter core     : 4.7.0
jupyter-notebook : 6.1.5
qtconsole        : 4.7.7
ipython          : 7.10.2
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.0.1
nbconvert        : 6.0.7
ipywidgets       : 7.5.1
nbformat         : 5.0.8
traitlets        : 5.0.5
```

**Comment by maxnoe** [comment]
Then it might be a linux specific problem. Anyways, it is not good to fix the bug-release of python for newcomers.

**Comment by Bultako** [comment]
This very specific version of Python in the environment was introduced to patch issue https://github.com/gammapy/gammapy/issues/2428 

Since we will no longer use `parfive` in `gammapy.download`, I can remove this pinned version of Python as well as the `parfive` dependency as the last commit of PR https://github.com/gammapy/gammapy/pull/3153

**Comment by adonath** [comment]
Thanks @Bultako!
