### ISSUE TITLE
Missing Zenodo community and Codemeta informations for ESCAPE

### ISSUE THREAD

**Issue by QRemy** [gammapy/gammapy#3847]
In order to complete the on-boarding of gammapy on the ESCAPE platform several actions are required : 

- edit the Zenodo entry to add it on ESCAPE 2020 community
see https://escape2020.pages.in2p3.fr/wp3/ossr-pages/page/contribute/publish_overview/ :
"Edit your project on Zenodo. Under “Communities” search for [“ESCAPE 2020”](https://zenodo.org/communities/escape2020) and add it. Save the record. This will trigger the curation process to the OSSR."
Who can do this ? @Bultako, @adonath, @registerrier, @bkhelifi 

- on zenodo the codemeta.json should be also uploaded outside of the zip file as in this example: https://zenodo.org/record/5972794#.YinUQhPMI6h

- the codemeta.jon should include informations about funder and funding grant 
as in the example below (from https://zenodo.org/record/5972794#.YinUQhPMI6h)
```
  "funder":[
    {
      "@type": "Organization",
      "name": "European Commission",
      "@id": "https://doi.org/10.13039/501100000780"
    }
  ],
  "funding": "824064",
```
could this be also included to the `CITATION.cff` or have to be added after conversion to `codemeta.json` ?

- the validity of the file json should be verified with the eossr codemeta validator:
 https://escape2020.pages.in2p3.fr/wp3/eossr/docstring_sources/eossr_cli/eossr-metadata-validator.html
could this be added to the workflow of #3833 ?

**Comment by Bultako** [comment]
Some comments on this..

- The [Gammapy Zenodo entry](https://zenodo.org/record/5721467) is linked to the Gammapy codebase GitHub repository, so that creating a release in GitHub would automatically trigger the creation of new release entry with a new DOI in Zenodo. 

**I think that this automatic action would not upload the `codemeta.json` outside the zip file, doing this needs a manual intervention and publishing a new version in Zenodo (with a new DOI). So I guess we need to disable the  automatic release trigger and publish the releases manually in Zenodo if we want to have the `codemeta.json` outside the zip file.** 

- ESCAPE 2020 community has been added to the metadata of the Zenodo record, as well as the CTAO Community. Though this is is not visible in the last published record of Gammapy in Zenodo, I hope it will be taken into account in the next published release record.

- [eossr codemeta validator](https://escape2020.pages.in2p3.fr/wp3/eossr/index.html) indeed can be used as one of the steps of the github actions in https://github.com/gammapy/gammapy/pull/3833. However we need to fine-tune the content of `codemeta.json` file generated by `cffconvert` and add the content below in order to have the  `codemeta.json` valid with `eossr`, which may also be done as a previous step in the github action.

```
  "softwareVersion": "0.18.2",
  "maintainer": "Gammapy developers",
  "readme": "Gammapy analyzes gamma-ray data and creates sky images, spectra and lightcurves, from event lists and instrument response information; it can also determine the position, morphology and spectra of gamma-ray sources. It is used to analyze data from H.E.S.S., Fermi-LAT, and the Cherenkov Telescope Array (CTA).",
  "funder":[
    {
      "@type": "Organization",
      "name": "European Commission",
      "@id": "https://doi.org/10.13039/501100000780"
    }
  ],
  "funding": "824064"
```

**Comment by vuillaut** [comment]
> In order to complete the on-boarding of gammapy on the ESCAPE platform several actions are required :
> 

> * on zenodo the codemeta.json should be also uploaded outside of the zip file as in this example: https://zenodo.org/record/5972794#.YinUQhPMI6h

This is not necessary anymore. Just add a codemeta.json to your repository and continue with the GitHub-Zenodo integration as usual.

**Comment by vuillaut** [comment]
> * ESCAPE 2020 community has been added to the metadata of the Zenodo record, as well as the CTAO Community. Though this is is not visible in the last published record of Gammapy in Zenodo, I hope it will be taken into account in the next published release record.

How has this been done? Directly on Zenodo web interface?
If so, the addition of the community should immediately trigger a curation request, which I did not receive.
Could you check please?

**Comment by adonath** [comment]
Thanks @vuillaut for your input here! I think the main goal of the workflow is to reduce the maintenance effort, the ideal solution would be indeed to keep the `CITATION.cff` and generate the `codemeta.json` and `.zenodo.json` on the fly. Using the eossr converter seems like a good solution to me, like:

`CITATION.cff -> cffconvert -> codemeta.json -> eossr converter -> .zenodo.json`

If there is still additional information to add by hand we could always introduce a separate manually maintained `ganmmapy-funding.yaml` or similar.

**Comment by vuillaut** [comment]
> The addition of ESCAPE 2020 community to the Gammapy Zenodo record has been done using the Zenodo web interface for record edition. There are two buttons when editing info on a record, `save` and `publish`. I guess the `publish` will create a new record with a new DOI, so I just clicked on the `save` button.

Actually no, you have to _publish_ your new metadata - it won't create a  new version, it concerns only the metadata.
You can test this in the [sandbox](https://sandbox.zenodo.org/).

> It is not clear to me how do we want to proceed to do on-boarding of gammapy on ESCAPE via Zenodo, in particular if publishing a new Zenodo record with a new DOI is mandatory.

Once done, we will receive the request for gammapy to be added to the community, that will [trigger the review process on our side](https://gitlab.in2p3.fr/escape2020/wp3/ossr-curation/-/merge_requests).
However, since we now require a codemeta file to be part of the record, it means we will have to wait for a new release of gammapy anyway.

> 
> In #3833 we already create a `.zenodo.json` using `cffconvert` from `CITATION.cff` main file, what is the advantage of using `eossr` converter from `codemeta.json` file instead ?

You codemeta **should** contain much more information than `CITATION.cff`. Part of this information will also be converted if using the `eossr` converter.

**Comment by Bultako** [comment]
@vuillaut 

I tried to produce a `.zenodo.json` file with [eossr](https://escape2020.pages.in2p3.fr/wp3/eossr/docstring_sources/eossr_cli/eossr-codemeta2zenodo.html) from this [codemeta.json](https://github.com/gammapy/gammapy/blob/codemeta/codemeta.json) file produced with `cffconvert`.

I have the following error trace log

```
$ eossr-codemeta2zenodo -i codemeta.json 
Traceback (most recent call last):
  File "/opt/miniconda3/envs/gammapy-dev/bin/eossr-codemeta2zenodo", line 33, in <module>
    sys.exit(load_entry_point('eossr', 'console_scripts', 'eossr-codemeta2zenodo')())
  File "/Users/jer/git/eossr/eossr/scripts/eossr_codemeta2zenodo.py", line 66, in main
    codemeta_file, outdir=directory_codemeta, overwrite=args.overwrite
  File "/Users/jer/git/eossr/eossr/metadata/codemeta2zenodo.py", line 311, in parse_codemeta_and_write_zenodo_metadata_file
    meta_converter.convert()
  File "/Users/jer/git/eossr/eossr/metadata/codemeta2zenodo.py", line 254, in convert
    self.zenodo_data = find_matching_metadata(self.codemeta_data)
  File "/Users/jer/git/eossr/eossr/metadata/codemeta2zenodo.py", line 200, in find_matching_metadata
    add_author_metadata(metadata_zenodo, codemeta_json[person_type], person_field=person_type)
  File "/Users/jer/git/eossr/eossr/metadata/codemeta2zenodo.py", line 83, in add_author_metadata
    zenodo_person = parse_person_schema_property(person_property, person_field)
  File "/Users/jer/git/eossr/eossr/metadata/codemeta2zenodo.py", line 47, in parse_person_schema_property
    zenodo_person['affiliation'] = person_property['affiliation']['name']
KeyError: 'name'
`` `

**Comment by vuillaut** [comment]
The generated `codemeta.json` is not valid as per codemeta online validator:

```
cffconvert -u https://raw.githubusercontent.com/gammapy/gammapy/b9a520c2ed257f5f87b2c3a0d3d2e397688fd49b/CITATION.cff -f codemeta -o codemeta.json
```

Then copy the content to https://codemeta.github.io/codemeta-generator/ will return
`Unknown field "legalName" in "affiliation"`

**Comment by vuillaut** [comment]
Then using the eossr metadata validator `eossr-metadata-validator codemeta.json`  also raises errors because of required metadata missing.

**Comment by Bultako** [comment]
After some tests with some metadata json content with the [eossr-codemeta2zenodo](https://escape2020.pages.in2p3.fr/wp3/eossr/docstring_sources/eossr_cli/eossr-codemeta2zenodo.html) and [eossr-metadata-validator](https://escape2020.pages.in2p3.fr/wp3/eossr/docstring_sources/eossr_cli/eossr-metadata-validator.html) tools, it seems `cffconvert` does not provide a good label for the name attribute of the affiliation (see https://github.com/citation-file-format/cff-converter-python/issues/272 issue filed by @vuillaut )

So until this is fixed I guess the content of the automatically generated `codemeta.json` that is produced in https://github.com/gammapy/gammapy/pull/3833 could be fixed in that GitHub action. Anyways, we also need to add some mandatory info requested by ESCAPE  to the `metadata.json`

**Comment by Bultako** [comment]
> In https://github.com/gammapy/gammapy/pull/3833 we already create a `.zenodo.json` using `cffconvert` from `CITATION.cff` main file, what is the advantage of using [eossr converter](https://escape2020.pages.in2p3.fr/wp3/eossr/docstring_sources/eossr_cli/eossr-codemeta2zenodo.html) from the `codemeta.json` file instead ?

I paste below the additional content in the `.zenodo.json` produced by the [eossr converter](https://escape2020.pages.in2p3.fr/wp3/eossr/docstring_sources/eossr_cli/eossr-codemeta2zenodo.html) with respect to the content produced by `cffconvert` from `CITATION.cff` main file.

```
    "grants": [
        {
            "id": "10.13039/501100000780::824064"
        }
    ],
    "related_identifiers": [
        {
            "identifier": "https://github.com/gammapy/gammapy",
            "relation": "isDerivedFrom",
            "resource_type": "software",
            "scheme": "url"
        }
    ],
    "communities": [
        {
            "identifier": "escape2020"
        }
    ],
    "upload_type": "software"
```

**Comment by Bultako** [comment]
I have modified https://github.com/gammapy/gammapy/pull/3833 so to comply with requirements on the `codemeta.json` from the ESCAPE community.

It uses eossr tools to validate `codemeta.json`  and convert into `.zenodo.json`

The final workflow is now:
`CITATION.cff -> cffconvert -> fix codemeta.json -> eossr validator -> eossr converter -> .zenodo.json`

**Comment by QRemy** [comment]
> the addition of the community should immediately trigger a curation request

@vuillaut
 Did you received the request with the latest update of gammapy or we still have to change something ?

**Comment by QRemy** [comment]
> the addition of the community should immediately trigger a curation request

@vuillaut
 Did you received the request with the latest update of gammapy or we still have to change something ?

**Comment by vuillaut** [comment]
> > the addition of the community should immediately trigger a curation request
> 
> @vuillaut Did you receive the request with the latest update of gammapy or we still have to change something ?

Wait... There is an issue with metadata I think.
We did receive the curation request:
https://gitlab.in2p3.fr/escape2020/wp3/ossr-curation/-/merge_requests/24

meaning that the escape2020 community was added to gammapy metadata.

However, the community does not appear anymore, see metadata of v0.20:
https://zenodo.org/record/6552377/export/json#.Yqhv0blBxB0

**Comment by Bultako** [comment]
@vuillaut 

Done.
