### ISSUE TITLE
setup.py develop option broken in master

### ISSUE THREAD

**Issue by joleroi** [gammapy/gammapy#432]
When I run
```
python setup.py develop
```
in the master branch I get this error

```
[/home/kingj/Software/gammapy] python setup.py develop
running develop
running egg_info
writing requirements to gammapy.egg-info/requires.txt
writing gammapy.egg-info/PKG-INFO
writing top-level names to gammapy.egg-info/top_level.txt
writing dependency_links to gammapy.egg-info/dependency_links.txt
writing entry points to gammapy.egg-info/entry_points.txt
reading manifest file 'gammapy.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.pxd' under directory 'gammapy'
warning: no files found matching '*.h' under directory 'gammapy'
warning: no files found matching '*' under directory 'scripts'
no previously-included directories found matching 'build'
no previously-included directories found matching 'docs/_build'
no previously-included directories found matching 'docs/api'
warning: no previously-included files matching '*.o' found anywhere in distribution
writing manifest file 'gammapy.egg-info/SOURCES.txt'
running build_ext
building 'gammapy._compiler' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/gammapy
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kingj/Software/miniconda3/envs/headsherpa/include/python2.7 -c gammapy/_compiler.c -o build/temp.linux-x86_64-2.7/gammapy/_compiler.o
gcc -pthread -shared -L/home/kingj/Software/miniconda3/envs/headsherpa/lib -Wl,-rpath=/home/kingj/Software/miniconda3/envs/headsherpa/lib,--no-as-needed build/temp.linux-x86_64-2.7/gammapy/_compiler.o -L/home/kingj/Software/miniconda3/envs/headsherpa/lib -lpython2.7 -o /home/kingj/Software/gammapy/gammapy/_compiler.so
skipping 'gammapy/detect/_test_statistics_cython.c' Cython extension (up-to-date)
building 'gammapy.detect._test_statistics_cython' extension
creating build/temp.linux-x86_64-2.7/gammapy/detect
gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/numpy/core/include -I/home/kingj/Software/miniconda3/envs/headsherpa/include/python2.7 -c gammapy/detect/_test_statistics_cython.c -o build/temp.linux-x86_64-2.7/gammapy/detect/_test_statistics_cython.o -Wp,-w -Wno-unused-function
gcc -pthread -shared -L/home/kingj/Software/miniconda3/envs/headsherpa/lib -Wl,-rpath=/home/kingj/Software/miniconda3/envs/headsherpa/lib,--no-as-needed build/temp.linux-x86_64-2.7/gammapy/detect/_test_statistics_cython.o -L/home/kingj/Software/miniconda3/envs/headsherpa/lib -lpython2.7 -o /home/kingj/Software/gammapy/gammapy/detect/_test_statistics_cython.so
Creating /home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/gammapy.egg-link (link to .)
gammapy 0.4.dev2030 is already the active version in easy-install.pth
Installing gammapy-spectrum-pfsim script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-bin script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-fit script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-derived script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-model-sherpa script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-pipe script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-model script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-spectrum-regions script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-data-select script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-detect-iterative script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-catalog-query script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-ts script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-lookup script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-detect script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-coordinates script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-test script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-catalog-simulate script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-cwt script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-data-manage script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Installing gammapy-image-significance script to /home/kingj/Software/miniconda3/envs/headsherpa/bin
Writing /tmp/easy_install-jklVoV/astropy-1.1.1/setup.cfg
Running astropy-1.1.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-jklVoV/astropy-1.1.1/egg-dist-tmp-m7nb8m
Traceback (most recent call last):
  File "setup.py", line 201, in <module>
    **package_info
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/develop.py", line 33, in run
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/develop.py", line 132, in install_for_development
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 719, in process_distribution
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 846, in resolve
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1091, in best_match
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/pkg_resources/__init__.py", line 1103, in obtain
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 639, in easy_install
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 669, in install_item
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 852, in install_eggs
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 1080, in build_and_install
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/easy_install.py", line 1066, in run_setup
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 242, in run_setup
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 166, in save_modules
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 141, in resume
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 154, in save_modules
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 239, in run_setup
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 269, in run
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 238, in runner
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/tmp/easy_install-jklVoV/astropy-1.1.1/setup.py", line 113, in <module>
    
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/bdist_egg.py", line 151, in run
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 185, in run
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 208, in find_sources
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 292, in run
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/egg_info.py", line 321, in add_defaults
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/sdist.py", line 131, in add_defaults
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/cmd.py", line 312, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/tmp/easy_install-jklVoV/astropy-1.1.1/astropy_helpers/astropy_helpers/commands/build_ext.py", line 263, in finalize_options
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/site-packages/setuptools-19.1.1-py2.7.egg/setuptools/command/build_ext.py", line 97, in finalize_options
  File "/home/kingj/Software/miniconda3/envs/headsherpa/lib/python2.7/distutils/command/build_ext.py", line 362, in check_extensions_list
    ("each element of 'ext_modules' option must be an "
setuptools.sandbox.UnpickleableException: DistutilsSetupError("each element of 'ext_modules' option must be an Extension instance or 2-tuple",)
```

**Comment by joleroi** [comment]
Sorry for the assignment mess ...

**Comment by joleroi** [comment]
This looks related

https://github.com/giampaolo/psutil/issues/723

**Comment by bsipocz** [comment]
It looks like setuptools 19.6 should solve it. 
@joleroi can you try and upgrade setuptools, and rerun ``python setup.py develop``?

**Comment by cdeil** [comment]
I have astropy=1.1.1 and setuptools=19.2 and don't see the issue.

@joleroi - Good luck!

**Comment by joleroi** [comment]
Thanks a lot for your help. Sorry, I am not very experienced with this kind of stuff.

Somehow it works now, I did the following
* remove gammapy installation by hand
* remove astropy
* re-install astropy (with conda) - this also let to an update of setuptools ```setuptools: 19.1.1-py27_0 --> 19.6.2-py27_0```

**Comment by cdeil** [comment]
Good that it works now.
Python packaging (setuptools, astropy-helpers, pip, conda) is pretty complicated.
Feel free to ask via GH issue or the Gammapy mailing list for help with such issues any time!

Close this issue?
