### ISSUE TITLE
MapDataset simulation with HpxGeom

### ISSUE THREAD

**Issue by Mitsunari-Takahashi** [gammapy/gammapy#5505]
**Gammapy version**
1.2. 
The result of `gammapy info` is below.

> System:
> 
> 	python_executable      : /Users/mitsunari/.conda/envs/gammapy-1.2/bin/python
> 	python_version         : 3.10.15
> 	machine                : x86_64
> 	system                 : Darwin
> 
> 
> Gammapy package:
> 
> 	version                : 1.2
> 	path                   : /Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy
> 

**Bug description**
`MapDataset.fake()` does not work with HpxGeom. 

**Expected behavior**
A count map is produced with the HEALPix spatial binning.

**To Reproduce**
Please try with the following code.

```
from astropy import units as u
from astropy.coordinates import SkyCoord
from gammapy.maps import HpxGeom, MapAxis
from gammapy.data import Observation, FixedPointingInfo
from gammapy.irf import load_irf_dict_from_file
from gammapy.makers import MapDatasetMaker
from gammapy.datasets import MapDataset
from gammapy.modeling.models import (
    ExpCutoffPowerLawSpectralModel,
    PointSpatialModel,
    SkyModel,
    FoVBackgroundModel,
)

# Please replace the following CTA IRF path with yours.
filename = "/Users/mitsunari/Downloads/cta-prod5-zenodo-fitsonly-v0.1/fits/CTA-Performance-prod5-v0.1-North-LSTSubArray-20deg.FITS/Prod5-North-20deg-AverageAz-4LSTs.180000s-v0.1.fits"
# Define observation
pointing = SkyCoord("0d", "0d")
irfs = load_irf_dict_from_file(filename)
obs = Observation.create(
    pointing=FixedPointingInfo(fixed_icrs=pointing),
    irfs=irfs,
    livetime="1h"
    )

# Create HpxGeom
# Define energy axis. Note that the name is fixed.
energy_axis = MapAxis.from_energy_bounds(
                0.01, 100.0, 20,
                unit="TeV", name="energy"
                )
energy_true_axis = MapAxis.from_energy_bounds(
                0.005, 200, 50,
                unit="TeV", name="energy_true")

# Restrict the geometry region
hpregion_str = 'DISK({lon},{lat},{rad})'.format(
                    lon=pointing.ra.degree,
                    lat=pointing.dec.degree,
                    rad=2)
geom = HpxGeom.create(
    nside=256,
    nest=True,
    region=hpregion_str,
    skydir=pointing,
    frame="icrs",
    axes=[energy_axis]
    )
''' If I use WcsGeom instead of HpxGeom, this does not make the error.
geom = WcsGeom.create(
                    skydir=pointing,
                    binsz=0.02,
                    width=(2, 2),
                    frame="icrs",
                    proj="CAR",
                    axes=[energy_axis],
                    )
'''

maker = MapDatasetMaker(selection=["background", "edisp", "psf", "exposure"])
empty_map = MapDataset.create(
                geom=geom,
                energy_axis_true=energy_true_axis,
                name="empty"
                )
map_dataset = maker.run(empty_map, obs)

models = [FoVBackgroundModel(dataset_name="dataset-mcmc")]
models.append(
                SkyModel(
                    spatial_model=PointSpatialModel(
                        lon_0=pointing.ra,
                        lat_0=pointing.dec,
                        frame="icrs"
                        ),
                    spectral_model=ExpCutoffPowerLawSpectralModel(
                        amplitude=1e-12 * u.Unit("cm-2 s-1 TeV-1"),
                        index=2,
                        lambda_=0.1 * u.Unit("TeV-1"),
                        reference=1 * u.TeV,
                        ),
                    name="test"
                )
            )
map_dataset.models = models
map_dataset.fake()
print(map_dataset.counts)
```

 I got the following error.

> (gammapy-1.2) mitsunari@White-CTA-iMac scripts % python test_hpx_geom.py
> Traceback (most recent call last):
>   File "/Users/mitsunari/anomaly_search/pbhstudy/bh-simulator/scripts/test_hpx_geom.py", line 85, in <module>
>     map_dataset.fake()
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/map.py", line 1339, in fake
>     npred = self.npred()
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/map.py", line 636, in npred
>     npred_total = self.npred_signal()
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/map.py", line 710, in npred_signal
>     evaluator.update(
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/evaluator.py", line 219, in update
>     self.psf = psf.get_psf_kernel(
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/astropy/utils/decorators.py", line 604, in wrapper
>     return function(*args, **kwargs)
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/irf/psf/map.py", line 290, in get_psf_kernel
>     factor = _psf_upsampling_factor(self, geom, position, precision_factor)
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/irf/psf/map.py", line 27, in _psf_upsampling_factor
>     psf_r68 = psf.containment_radius(
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/irf/psf/map.py", line 219, in containment_radius
>     coords = self._get_irf_coords(**kwargs)
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/irf/psf/map.py", line 157, in _get_irf_coords
>     lon_pix, lat_pix = geom.coord_to_pix(coords.skycoord)
> ValueError: not enough values to unpack (expected 2, got 1)

**Other information**
I guess the cause of the error is that `HpxGeom.coord_to_pix` returns a single pixel number of HEALPix instead of the two pixel numbers of the X and Y axes.

**Comment by bkhelifi** [comment]
Thank you a lot for this feedback. We are not testing enough the HPX features!
I will work on it in more depth in preparation of the next LTS (v2.0)

**Comment by Mitsunari-Takahashi** [comment]
Thank you for the answer. I'm considering to contribute to this issue if it is fine with the developers.

**Comment by registerrier** [comment]
Thanks @Mitsunari-Takahashi . 
 
The `HpxGeom` is not yet supported on the `MapDataset`. In particular, the `PSFMap` does not support healpix geometry  (e.g. here `PSFMap.get_psf_kernel()` is failing).

In practice, what we had discussed so far is that `MapEvaluator` of a dataset with `Hpx` geometry should use tangent `Wcs` geometries to perform PSF convolutions. Can you comment @adonath @LauraOlivera ?

**Comment by Mitsunari-Takahashi** [comment]
Thank you for the reply @registerrier .

> In practice, what we had discussed so far is that MapEvaluator of a dataset with Hpx geometry should use tangent Wcs geometries to perform PSF convolutions. 

Could you explain this idea a bit more when you have time?

**Comment by adonath** [comment]
The support for Healpix in Gammapy is not well documented, however computing predicted counts and faking events should work. We have a test for it here: https://github.com/gammapy/gammapy/blob/main/gammapy/datasets/tests/test_map.py#L2170

As @registerrier mentioned the `PSFMap` does not support healpix geometries yet (we should probably check and raise a more meaningful error).  But there is no need to work with helix IRF maps. You can actually mix geometries. If I remember correctly this is what @LauraOlivera did for the HAWC validation. She used healpix for the counts, exposure and background maps, while the IRFs were stored in WCS all sky maps. Which was convenient because the IRFs were almost in this format anyway. 

@Mitsunari-Takahashi I am not 100% about your use case, but changing the IRF map geometries to WCS should just work fine. Along the lines of:

```python
from gammapy.datasets import create_map_dataset_geoms, MapDataset
from gammapy.maps import HpxGeom, MapAxis


energy_axis = MapAxis.from_energy_bounds(
                0.01, 100.0, 20,
                unit="TeV", name="energy"
                )

energy_true_axis = MapAxis.from_energy_bounds(
                0.005, 200, 50,
                unit="TeV", name="energy_true")

hpregion_str = 'DISK({lon},{lat},{rad})'.format(
                    lon=0,
                    lat=0,
                    rad=2)


geom = HpxGeom.create(
    nside=256,
    nest=True,
    region=hpregion_str,
    skydir=pointing,
    frame="icrs",
    axes=[energy_axis]
)

geoms = create_map_dataset_geoms(geom=geom, energy_axis_true=energy_true_axis)

geoms["geom_psf"] = geoms["geom_psf"].to_wcs_geom()
geoms["geom_edisp"] = geoms["geom_edisp"].to_wcs_geom()

dataset = MapDataset.from_geoms(**geoms)
```
So the part the @registerrier mentioned is already working. Improving the support for Healpix in Gammapy would mean mostly more testing and better documentation. We might think about adding support got Helix germs in IRF maps, but I think this is not a priority.

**Comment by Mitsunari-Takahashi** [comment]
Thank you very much for the detailed description! @adonath The feature of mixing geometries will benefit many people.
I tried it and then the above error disappeared, but another one happened:

> (gammapy-1.2) mitsunari@White-CTA-iMac bh-simulator % python /Users/mitsunari/anomaly_search/pbhstudy/bh-simulator/scripts/test_hpx_geom.py
> Model {m.name} is outside the target geom but contributes inside through the psf.This contribution cannot be estimated precisely.Consider extending the dataset geom and/or the masked margin in the mask_fit.
> Traceback (most recent call last):
>   File "/Users/mitsunari/anomaly_search/pbhstudy/bh-simulator/scripts/test_hpx_geom.py", line 95, in <module>
>     map_dataset.fake()
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/map.py", line 1339, in fake
>     npred = self.npred()
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/map.py", line 636, in npred
>     npred_total = self.npred_signal()
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/map.py", line 710, in npred_signal
>     evaluator.update(
>   File "/Users/mitsunari/.conda/envs/gammapy-1.2/lib/python3.10/site-packages/gammapy/datasets/evaluator.py", line 237, in update
>     self.exposure = exposure._cutout_view(
> AttributeError: 'HpxNDMap' object has no attribute '_cutout_view'

 I'm trying to investigate this by myself.

**Comment by Astro-Kirsty** [comment]
Hello @Mitsunari-Takahashi, feel free to create a pull request with this branch. Then we can properly review the work :)
