### ISSUE TITLE
Issues with  ExclusionMask.distance

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#587]
While working on #558 , I noticed this issue with `ExclusionMask.distance`:
```python
>>> from gammapy.image import ExclusionMask
>>> mask = ExclusionMask.empty((300, 200))
>>> mask.distance_image
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/utils/decorators.py", line 496, in __get__
    return obj.__dict__[self._key]
KeyError: 'distance_image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/utils/decorators.py", line 498, in __get__
    val = self.fget(obj)
  File "/Users/deil/code/gammapy/gammapy/image/mask.py", line 99, in distance_image
    return exclusion_distance(self.mask)
  File "/Users/deil/code/gammapy/gammapy/image/utils.py", line 294, in exclusion_distance
    distance_inside = distance_transform_edt(np.invert(exclusion))
TypeError: ufunc 'invert' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

@OlgaVorokh - Could you please fix this?

- [ ] Start by adding a test to reproduce the issue.
- [ ] Then move the code from the standalone function [here](https://github.com/gammapy/gammapy/blob/7a9087b544a21846aeed0e8073271e973baf7f23/gammapy/image/utils.py#L270) inside the `ExclusionMask.distance_image` method.
- [ ] Investigate and fix the issue ... maybe a manual change in `dtype` is needed to get it to work?

Let me know if you don't have time for this soon, then I might do this as part of #558.

**Comment by cdeil** [comment]
Fixed by @OlgaVorokh in #631.
