### ISSUE TITLE
SNRcat download error

### ISSUE THREAD

**Issue by cdeil** [gammapy/gammapy#670]
Reminder issue for myself: fix this:

```
$ python make_snrcat.py 
Downloading http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=SNR [Done]
Downloading http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=OBS [Done]
Traceback (most recent call last):
  File "make_snrcat.py", line 6, in <module>
    cat = SourceCatalogSNRcat()
  File "/Users/deil/code/gammapy/gammapy/catalog/snrcat.py", line 50, in __init__
    self.obs_table = _fetch_catalog_snrcat_obs_table(cache=cache)
  File "/Users/deil/code/gammapy/gammapy/catalog/snrcat.py", line 124, in _fetch_catalog_snrcat_obs_table
    table = Table.read(filename, format='ascii.csv', header_start=1, delimiter=';')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/table/table.py", line 2332, in read
    return io_registry.read(cls, *args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/io/registry.py", line 351, in read
    data = reader(*args, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/io/ascii/connect.py", line 37, in io_read
    return read(filename, format=format, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/astropy/io/ascii/ui.py", line 289, in read
    table = fileobj.read()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 15893: invalid start byte
```

**Comment by cdeil** [comment]
I'm still getting this error:
```
In [1]: from gammapy.catalog import SourceCatalogSNRcat

In [2]: cat = SourceCatalogSNRcat()
Downloading http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=SNR [Done]
Downloading http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=OBS [Done]
---------------------------------------------------------------------------
UnicodeDecodeError                        Traceback (most recent call last)
<ipython-input-2-e442bb6cf37a> in <module>()
----> 1 cat = SourceCatalogSNRcat()

/Users/deil/Library/Python/3.5/lib/python/site-packages/gammapy/catalog/snrcat.py in __init__(self, cache)
     48         # At least optionally?
     49         self.snr_table = _fetch_catalog_snrcat_snr_table(cache=cache)
---> 50         self.obs_table = _fetch_catalog_snrcat_obs_table(cache=cache)
     51 
     52         super(SourceCatalogSNRcat, self).__init__(table=self.snr_table)

/Users/deil/Library/Python/3.5/lib/python/site-packages/gammapy/catalog/snrcat.py in _fetch_catalog_snrcat_obs_table(cache)
    122 
    123     # Note: currently the first line contains this comment, which we skip via `header_start=1`
--> 124     table = Table.read(filename, format='ascii.csv', header_start=1, delimiter=';')
    125     table.meta['url'] = url
    126     table.meta['version'] = _snrcat_parse_download_date(filename)

/Users/deil/code/astropy/astropy/table/table.py in read(cls, *args, **kwargs)
   2428         passed through to the underlying data reader (e.g. `~astropy.io.ascii.read`).
   2429         """
-> 2430         return io_registry.read(cls, *args, **kwargs)
   2431 
   2432     def write(self, *args, **kwargs):

/Users/deil/code/astropy/astropy/io/registry.py in read(cls, *args, **kwargs)
    466 
    467         reader = get_reader(format, cls)
--> 468         data = reader(*args, **kwargs)
    469 
    470         if not isinstance(data, cls):

/Users/deil/code/astropy/astropy/io/ascii/connect.py in io_read(format, filename, **kwargs)
     35     from .ui import read
     36     format = re.sub(r'^ascii\.', '', format)
---> 37     return read(filename, format=format, **kwargs)
     38 
     39 

/Users/deil/code/astropy/astropy/io/ascii/ui.py in read(table, guess, **kwargs)
    296             try:
    297                 with get_readable_fileobj(table) as fileobj:
--> 298                     table = fileobj.read()
    299             except ValueError:  # unreadable or invalid binary file
    300                 raise

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py in decode(self, input, final)
    319         # decode input (taking the buffer into account)
    320         data = self.buffer + input
--> 321         (result, consumed) = self._buffer_decode(data, self.errors, final)
    322         # keep undecoded input until the next call
    323         self.buffer = data[consumed:]

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 16017: invalid start byte
```

**Comment by cdeil** [comment]
Non-characters removed by Gilles Ferrand just now.

This works again:
```
$ python
>>> from gammapy.catalog import SourceCatalogSNRcat
>>> SourceCatalogSNRcat()
Downloading http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=SNR [Done]
Downloading http://www.physics.umanitoba.ca/snr/SNRcat/SNRdownload.php?table=OBS [Done]
<gammapy.catalog.snrcat.SourceCatalogSNRcat object at 0x1023bc1d0>
```

Closing issue now.

(if this comes up again in the future, we should change the Gammapy code to replace non-ascii characters with a default ascii character on read to make this more robust)
